name: slm-rag
dependencies:
  - python=3.10
  - pip
  - pip:
      - langchain==0.2.13
      - langchain-community==0.2.12
      - langchain-huggingface==0.0.3
      - faiss-cpu
      - sentence-transformers
      - pypdf
      - huggingface-hub
      - matplotlib
      - scikit-learn
      - umap-learn